// User data in JSON objects
module.exports = [
    {
        user_username:'gurpreet',
        user_password:'123',
        user_email:'gurpreet@mapple.ca'
    },
    {
        user_username:'soma',
        user_password:'123',
        user_email:'soma@mapple.ca'
    },
    {
        user_username:'jessica',
        user_password:'123',
        user_email:'jessica@mapple.ca'
    },
    {
        user_username:'minion',
        user_password:'123',
        user_email:'minion@mapple.ca'
    },
    {
        user_username:'bob',
        user_password:'123',
        user_email:'bob@mapple.ca'
    },
    {
        user_username:'erica',
        user_password:'123',
        user_email:'erica@mapple.ca'
    },
    {
        user_username:'garfield',
        user_password:'123',
        user_email:'garfield@mapple.ca'
    }
]

